'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import type {Article,Category} from '@/lib/types'

const empty={title:'',slug:'',dek:'',hero_text:'',hero_image:'',category_id:'',reading_minutes:'8',status:'draft',body:''}
export default function AdminStudio(){
 const supabase=createClient();const [user,setUser]=useState<any>(null);const [auth,setAuth]=useState({email:'',password:''});const [articles,setArticles]=useState<Article[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [form,setForm]=useState<any>(empty);const [editing,setEditing]=useState<number|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 async function load(){const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user)return;const [{data:a},{data:c}]=await Promise.all([supabase.from('articles').select('*,categories(name,slug)').order('updated_at',{ascending:false}),supabase.from('categories').select('*').order('name')]);setArticles((a??[]) as Article[]);setCategories((c??[]) as Category[])}
 useEffect(()=>{load();const {data}=supabase.auth.onAuthStateChange(()=>load());return()=>data.subscription.unsubscribe()},[])
 const admin=user?.app_metadata?.role==='admin'
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword(auth);setMessage(error?.message||'Signed in.');setBusy(false);if(!error)load()}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const payload={title:form.title,slug:form.slug||form.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),dek:form.dek,hero_text:form.hero_text,hero_image:form.hero_image||null,category_id:form.category_id?Number(form.category_id):null,reading_minutes:Number(form.reading_minutes)||null,status:form.status,body:form.body.split('\n\n').map((x:string)=>x.trim()).filter(Boolean),published_at:form.status==='published'?(new Date().toISOString()):null,updated_at:new Date().toISOString()};const q=editing?supabase.from('articles').update(payload).eq('id',editing):supabase.from('articles').insert(payload);const {error}=await q;setMessage(error?.message||'Saved.');setBusy(false);if(!error){setForm(empty);setEditing(null);load()}}
 function edit(a:Article){setEditing(a.id);setForm({title:a.title,slug:a.slug,dek:a.dek||'',hero_text:a.hero_text||'',hero_image:a.hero_image||'',category_id:a.category_id?String(a.category_id):'',reading_minutes:String(a.reading_minutes||8),status:a.status,body:(a.body||[]).join('\n\n')});window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(id:number){if(!confirm('Delete this story?'))return;const {error}=await supabase.from('articles').delete().eq('id',id);setMessage(error?.message||'Deleted.');load()}
 if(!user)return <div className="adminwrap"><div className="adminlogin"><div className="kicker">Kya Scene Hai?</div><h1>EDITORIAL<br/>STUDIO.</h1><p>Sign in with your Supabase account to manage the newsroom.</p><form onSubmit={login} className="adminform"><input type="email" placeholder="Editor email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})} required/><input type="password" placeholder="Password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})} required/><button disabled={busy}>{busy?'Signing in…':'Enter studio →'}</button></form>{message&&<p className="adminmsg">{message}</p>}</div></div>
 if(!admin)return <div className="adminwrap"><div className="adminlogin"><div className="kicker">Signed in</div><h1>NO<br/>ACCESS.</h1><p>Your account is authenticated, but it does not have the <b>admin</b> app_metadata role required for the editorial studio.</p><p className="adminhint">In Supabase Auth, set your user's App Metadata to <code>{`{"role":"admin"}`}</code>, then sign out and back in.</p><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></div>
 return <div className="adminwrap"><header className="adminbar"><a href="/" className="logo"><span>KYA SCENE HAI?</span></a><div><a href="/">View site</a><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></header><main className="adminmain"><div className="adminhead"><div><div className="kicker">Editorial Studio</div><h1>{editing?'EDIT STORY':'NEW STORY'}</h1></div><button className="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>+ New story</button></div><form className="editor" onSubmit={save}><div className="editorgrid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="auto-generated if blank"/></label><label className="wide">Dek<textarea value={form.dek} onChange={e=>setForm({...form,dek:e.target.value})}/></label><label>Category<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})} required><option value="">Choose…</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Reading minutes<input type="number" min="1" value={form.reading_minutes} onChange={e=>setForm({...form,reading_minutes:e.target.value})}/></label><label>Hero text<input value={form.hero_text} onChange={e=>setForm({...form,hero_text:e.target.value})}/></label><label>Hero image URL<input value={form.hero_image} onChange={e=>setForm({...form,hero_image:e.target.value})} placeholder="Optional public image URL"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="wide">Story body<textarea className="bodyarea" value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Write one paragraph per block. Separate paragraphs with a blank line."/></label></div><div className="editoractions"><button disabled={busy}>{busy?'Saving…':editing?'Update story':'Save story'}</button>{message&&<span>{message}</span>}</div></form><section className="storytable"><div className="kicker">Newsroom</div><h2>STORIES</h2>{articles.map(a=><div className="storyrow" key={a.id}><div><strong>{a.title}</strong><small>{a.categories?.name||'Uncategorized'} · {a.status}</small></div><div><button className="secondary" onClick={()=>edit(a)}>Edit</button><button className="danger" onClick={()=>remove(a.id)}>Delete</button></div></div>)}</section></main></div>
}
